### ISSUE TITLE
names with dashes and colons

### ISSUE THREAD

**Issue by liquidizer** [fauxparse/close-tags#13]
XML allows tag and attribute names to have dashes, colons and dots. The web framework angular uses dashes a lot. The colon is essential for all XML documents with different name spaces. Unfortunately, close-tags does not recognize this. For the following open tags, no close tags are inserted:

<ng-include src="...">
<div ng-show="...">
<svg:use xlink:href="....">

http://www.xml.com/pub/a/2001/07/25/namingparts.html

Thanks for fixing,
Stefan

**Comment by fauxparse** [comment]
Thanks! Fixed in v0.6.0.

**Comment by ghost** [comment]
Hi,
thank you for the update. I installed it just now and did not see it
work. I only realized a strange new behavior. Sometimes two tags are
closed at once, e.g. <a><b> both get closed with one activation of the
plugin.

Thanks for your efforts,
Stefan

**Comment by fauxparse** [comment]
Hi Stefan,

Thanks for checking this out. However, I can't reproduce the behaviour you're seeing, and the original issue is definitely fixed for me.

At this stage I don't have much time or use for this plugin, as I've moved from Atom to Vim full time. If it's still useful to you, I'll happily accept pull requests :)

Thanks,
Matt
